### ISSUE TITLE
Unexpected keyword argument in __init__() of BaseModelOutputWithPast

### ISSUE THREAD

**Issue by BlackieMia** [Cardinalere/Batch-ICL#1]
I got the following error when running `bash Batch-ICL.sh` after following the instruction and substitute the source code of `transformers`. It seems like the class `BaseModelOutputWithPast` in `transformers/modeling_outputs.py` should be correspondingly changed since it originally does not adopt 'hidden_before_mlp' as its initialization parameter.
```
Traceback (most recent call last):
  File "Batch-ICL.py", line 426, in <module>
    main(args.param_size, args.model_type, args.task)
  File "Batch-ICL.py", line 354, in main
    lay = get_layer(tokenizer,model,dev_df,val_df,tot_l,task)
  File "Batch-ICL.py", line 320, in get_layer
    hiddens,_ = batch_get_hidden(model,tokenizer,[record['prompt'] for record in records_1shots],k,val_df.shape[0],pos=-2)
  File "Batch-ICL.py", line 186, in batch_get_hidden
    outp = model(**encode_inputs, output_hidden_states = True, return_dict = True,out_attn=True,idea=0)#["hidden_states"]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1678, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1580, in forward
    return BaseModelOutputWithPast(
TypeError: __init__() got an unexpected keyword argument 'hidden_before_mlp'
```

**Comment by Cardinalere** [comment]
Thank you for your feedback! We apologize for the inconvenience you encountered while running '`Batch-ICL.sh`', and we appreciate you uploading the relevant files.

To address the issue you encountered, we have reviewed the files you mentioned and identified the problem. You are correct that the '`BaseModelOutputWithPast`' class in '`transformers/modeling_outputs.py`' needs to be correspondingly modified to support '`hidden_before_mlp`' as its initialization parameter.

We have addressed this issue and release an updated version.

If you need any further assistance or have any other questions, please feel free to let us know. Once again, thank you for your feedback and patience!I hope this reply is helpful to you!
